# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Logical Foundations of Computing
author: CPSC 510

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - content/references.bib

# Exclude files from being processed
exclude_patterns:
  - "README.md"
  - "lecture-by-lecture.md"
  - "local/**"
  - "overview.md"
  - "notes/**"
  - ".venv/**"
  - "z3/**"
  - "playground/**"
  - "src/**"
  - "notebooks/**"
  - "prompts/**"
  - "literature/**"
  - "docs/**"

# Information about where the book exists on the web
repository:
  url: https://github.com/LEAP-at-Chapman/CPSC-510-Logical-Foundations-of-Computing

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  expand_sections: true
  home_page_in_navbar: false

parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default!
    - amsmath
    - dollarmath

sphinx:
  config:
    html_title: "Logical Foundations of Computing"
    html_extra_path: ["content/examples"]
    html_baseurl: https://leap-at-chapman.github.io/CPSC-510-Logical-Foundations-of-Computing/
    latex_elements:
      preamble: |
        \usepackage{stmaryrd}
    bibtex_reference_style: author_year
    mathjax3_config:
      tex:
        macros:
          Set: ["{\\sf Set}", 0]
          Qu: ["{\\Omega}", 0]
          QuCat: ["{\\Omega\\text{-cat}}", 0]
          One: ["{\\mathbb{1}}", 0]
          yo: ["ã‚ˆ", 0]
          bigsqcap: ["\\sqcap", 0]
